print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What time did the man go to the  dentist?')
input()
print('Tooth hurt-y')
print()
print("Why do chicken coops only have 2 doors?")
input()
print("Because if they had four, they would be ckicken sedans")
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Dr')
input()
print('Dr Who?')
input()
print('Surely you mean Dr Whom', end='')
print('?')
input()

print("\n\nPress enter to exit")
